### ISSUE TITLE
Support for brackets in location

### ISSUE THREAD

**Issue by hvamstel** [pieter-edelman-nictiz/hl7-fhir-validator-action#3]
Some of the locations that we use in the script have brackets e.g.
Bundle.entry[*].resource.ofType(Group).code

Currently the regex.match does not find a match. This is because the brackets ( and ) need to be escaped with a \

After this fix matching locations with brackets works as expected.

**Comment by hvamstel** [comment]
I have already created a pull request for this. #2

**Comment by pieter-edelman-nictiz** [comment]
Fix has been merged!
